### ISSUE TITLE
Missing required parameter "url"

### ISSUE THREAD

**Issue by impredicative** [html-preview/html-preview.github.io#4]
When using the web form at https://html-preview.github.io/ , if a URL is submitted, the result is the error message:

> Missing required parameter "url"

Note that the form takes me to the page `https://html-preview.github.io/?<target_url>`.

In contrast, if I visit ` https://html-preview.github.io/?url=<target_url>`, it works fine. In summary, it doesn't work without explicitly specifying `url=`. Can this be fixed?

**Comment by hoijui** [comment]
yunruse fixed it a while ago, but I did not see it, sorry!
It is merged now.
Thanks for the report.
